### ISSUE TITLE
Outdated link to MerossIOT

### ISSUE THREAD

**Issue by xsanda** [bytespider/Meross#10]
The URL in the intro of [MQTT wiki page](https://github.com/bytespider/Meross/wiki/MQTT/35f29c2d0c4d912b256cb57734f014484085d759) is outdated, the code now seems to be here: https://github.com/albertogeniola/MerossIot/blob/0.4.X.X/meross_iot/manager.py

**Comment by bytespider** [comment]
Link updated. Thanks.
