### ISSUE TITLE
The wiki references some '--user', but cannot find how to use it

### ISSUE THREAD

**Issue by almico** [bytespider/Meross#21]
On [this page](https://github.com/bytespider/Meross/wiki/MQTT) I read the following:

```
user is the string you provided with --user and key is the strig you provided with --key on setup.
```

but I cannot find any other reference to that `--user` (and `--key`).
Could you, please, clarify?
Thank you 🥰

**Comment by bytespider** [comment]
Hi.

When you set up the device using `meross setup` you can optionally pass a string to `--user` and `--key`. The device will then use those strings when generating the credentials it passes on authentication with your broker.
