### ISSUE TITLE
Default user is "undefined"

### ISSUE THREAD

**Issue by Skyleiger** [bytespider/Meross#26]
Hi,
After a short desperation and a bit of debugging i found out that the user, if you don't specify it during setup, is not 0 but "undefined", so the displayed password is wrong.
This is also the case if the user string is too long (or similar?). 

Sincerely,
Dominic

**Comment by bytespider** [comment]
Hi Dominic

I had discovered the `undefined` issue but had not committed the code as life got in the way. I've just published 1.0.10 to github and NPM if you want to try that

**Comment by Skyleiger** [comment]
Thank you, then that's settled. Don't forget to create a new release ;)

**Comment by bytespider** [comment]
@Skyleiger did the code work for you?
