### ISSUE TITLE
Should the user-id be an integer?

### ISSUE THREAD

**Issue by nao-pon** [bytespider/Meross#31]
First of all, thank you for developing a great tool.

In previous versions I configured it with a string for user-id and used it fine, but recent versions seem to only accept user-id integers.

Is the reason for such a change to cause something wrong?

**Comment by bytespider** [comment]
Yes the user id corresponds to the literal I'd within the Meross database. It was previously thought that it was the account username.and so we could use.any string for our purposes.

In my opinion there is no reason to use --user or --key as they don't provide any additional security for your devices unless you are on a public network.
