### ISSUE TITLE
Wiki: How is the Mac address formatted for the password?

### ISSUE THREAD

**Issue by a-waider** [bytespider/Meross#38]
The wiki states that the iot device is connecting to the MQTT broker wit a password like `{user}_md5({MAC}{key})`. I'm wondering how the Mac address is formatted. Can anyone make up an example?

**Comment by bytespider** [comment]
Colon separated octets. https://github.com/bytespider/Meross/blob/7a9ea926d3479b6a90dff256c59547c57f7614aa/lib/api.js#L195
