### ISSUE TITLE
Unable to make it work

### ISSUE THREAD

**Issue by DanyGijon** [bytespider/Meross#40]
This project looks really nice but tried today to reconfigure MSS210 and MSS310 so to use local mqtt servers but those are not even able to connect to the WiFi network and get stucked just blinking green. Had to recover them using Meross APP. 

Setup command didn´t  report any error though. I´m testing this from OSX 11.2.1

Any idea how I can troubleshoot this?

Thanks

**Comment by bytespider** [comment]
Can you give some detail about your setup?
What MQTT broker? How is MQTT set up? Are you using Home Assistant?

**Comment by DanyGijon** [comment]
mqtt configured using mosquitto as per example provided (Minimal unauthenticated), except port which I use 1883,  on Home Assistant Core deployment. 


However the issue right now is that not even able to see the device joining Wifi Network. setup command is the following: 
./meross setup --gateway 10.10.10.1 --wifi-ssid RoDaniH --wifi-pass ******** --mqtt mqtts://192.168.68.100:1883

┌────────────────────┬────────────────────────────────────────────────────────────────────
│Device              │mss210 us mt7682 (hardware:2.0.0 firmware:2.2.2)                    
├────────────────────┼────────────────────────────────────────────────────────────────────
│UUID                │19011804581223251h0434298f1a4b07                                    
├────────────────────┼────────────────────────────────────────────────────────────────────
│Mac address         │34:29:8f:1a:4b:07                                                   
├────────────────────┼────────────────────────────────────────────────────────────────────
│IP address          │10.10.10.1                                                          
├────────────────────┼────────────────────────────────────────────────────────────────────
│Current MQTT broker │192.168.68.100:1883                                                 
├────────────────────┼────────────────────────────────────────────────────────────────────
│Credentials         │User: 34:29:8f:1a:4b:07                                             
│                    │Password: -----------------------------------------                       
├────────────────────┼────────────────────────────────────────────────────────────────────
│MQTT topics         │Publishes to: /appliance/19011804581223251h0434298f1a4b07/publish   
│                    │Subscribes to: /appliance/19011804581223251h0434298f1a4b07/subscribe
└────────────────────┴────────────────────────────────────────────────────────────────────
Device will reboot...


Nothing on mosquitto: 

sh-3.2$ mosquitto_sub -h 192.168.68.100 -p 1883  -t "/appliance/19011804581223251h0434298f1a4b07/publish" --cafile /Users/user/ca-meross.crt

**Comment by bytespider** [comment]
Meross devices **can only** use port 8883

**Comment by DanyGijon** [comment]
You are certainly right. I have re run setup and reconfigure mqtt and now mss210 is showing up on mosquitto and home assistant. Couple of questions though: 
- Is it expected that MS210 led keeps blinking green instead of solid green when working on cloud?
- Also, HA only works for turning the swith off as when I do so, entity becomes unresponsive on home assistant until manually turned on 
Thanks

**Comment by bytespider** [comment]
Sorry, I don't have any experience with the MSS210. However, I expect it's still flashing as it's unable to connect to something or isn't receiving some kind of configuration complete signal. It would be with seeing what messages it sends to your broker.

What integration are you using to control the device? It's possible they have not implemented the device status in a way that works for this device.

**Comment by DanyGijon** [comment]
I´m working with Meross LAN on Home Assistant. I guess I´ll have to follow this investigation up with them.

Thanks a lot for your help

**Comment by bytespider** [comment]
They are great at Meross LAN, they'll get you set up in no time.
