### ISSUE TITLE
Mosquitto errors with Meross PowerStrip

### ISSUE THREAD

**Issue by alfem** [bytespider/Meross#42]
Hi!

First at all, what a great work setting these Meross devices cloud-free! Thanks a lot!

Unfortunately I tried your setup script on a Meross Power Strip and it seemed to work. My powerstrip now is linked to my access point (green light blinking quickly forever), and connects to my mosquitto server, but I only get loads of lines like this:
 
```
1637259948: Socket error on client <unknown>, disconnecting.
1637259951: New connection from 192.168.1.122 on port 1883.
1637259951: Socket error on client <unknown>, disconnecting.
1637259954: New connection from 192.168.1.122 on port 1883.
1637259954: Socket error on client <unknown>, disconnecting.
1637259957: New connection from 192.168.1.122 on port 1883.
```
The command I used is this:

`npx meross setup --gateway 10.10.10.1 --wifi-ssid WLAN_XX --wifi-pass XXXXXXXX --mqtt mqtt://192.168.1.15`

No password or certificates implied. 

My device is identifies as _mss425e eu MT7687 (hardware:1.0.0 firmware:1.1.9)_ 

Do I need the user and password your tool shows in mosquito configuration?

**Comment by bytespider** [comment]
Meross devices typically (I don't know if all do) require TLS so you'll need to set up a certificate and probably port 8883
