### ISSUE TITLE
Devices are "lost"  on Meross Lan

### ISSUE THREAD

**Issue by hampelo** [bytespider/Meross#46]
I rebooted my router and since have "lost"  several meross devices.  It is possible they have changed IP.

meross lan:  2.5.5
HA:  2022.2.9

Can these devices be recovered?  Do I need to remove and read the integration?

**Comment by bytespider** [comment]
If the Led on the devices is green then that would suggest they can connect to the network and the broker (cloud or local).

**Comment by hampelo** [comment]
All devices work physically and work fine through the meross app so the connection to the network is good.  They have simply become "unavailable" to HA.  Not all of them, just 5 or 6 of the 30.

**Comment by bytespider** [comment]
This is an issue for Meross LAN then, since it's unrelated to this tool.
