### ISSUE TITLE
Upgraded firmware/incorrect key

### ISSUE THREAD

**Issue by skug67** [bytespider/Meross#62]
I just upgraded the firmware on my MSG100 (w/HomeKit) to version 4.2.6 and now both meross-info and meross-setup (both previously working) are failing with the error message "Incorrect shared key provided"

**Comment by bytespider** [comment]
@skug67 Sorry for the delay. I have published a new version today which implements the new method for sending wifi credentials thanks to @DominikGebhart. Perhaps if you try with `--use-wifi-x` you'll have luck.

**Comment by skug67** [comment]
I ended up returning my Meross device and buying an OpenGarage unit.  So can't really try this out....Sent from my iPadOn Nov 1, 2023, at 8:30 AM, Rob Griffiths ***@***.***> wrote:﻿
@skug67 Sorry for the delay. I have published a new version today which implements the new method for sending wifi credentials thanks to @DominikGebhart. Perhaps if you try with --use-wifi-x you'll have luck.
