### ISSUE TITLE
Working with mss100

### ISSUE THREAD

**Issue by bgnt44** [bytespider/Meross#7]
Very interested in your work , any chance it works with mss100 and other Meross plugs ?

**Comment by bytespider** [comment]
I do not know. I don't own one.

By all means try it

--
Rob Griffiths
http://bytespider.eu

https://github.com/bytespider

**Comment by bgnt44** [comment]
I can confirm it works

**Comment by bytespider** [comment]
Thanks for testing it.

--
Rob Griffiths
http://bytespider.eu

https://github.com/bytespider
